### ISSUE TITLE
Maven binary fails to launch

### ISSUE THREAD

**Issue by curiousercreative** [perfectsense/training#9]
When downloading the linked Maven `mvn` binary (3.5.2; also tried 3.6.2) and manually moving to `usr/local/bin`, `mvn` fails with error:
```
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
```

macOS 10.14.6 (18G95)

**Comment by BrennanEbeling** [comment]
We use Gradle to build the project now so I don't think this is applicable anymore
